### ISSUE TITLE
Pip version is broken

### ISSUE THREAD

**Issue by guillaumevincent** [goneri/dci-lite#3]
After a pip install dci, I got the following error:

```
Traceback (most recent call last):
  File "/home/guillaume/workspace/dci-client/venv/bin/dcictl", line 11, in <module>
    load_entry_point('dciclient', 'console_scripts', 'dcictl')()
  File "/home/guillaume/workspace/dci-client/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/guillaume/workspace/dci-client/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/guillaume/workspace/dci-client/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/guillaume/workspace/dci-client/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/guillaume/workspace/dci-client/client/core.py", line 3, in <module>
    import dci.client
  File "/home/guillaume/workspace/dci-client/venv/lib64/python3.7/site-packages/dci/client.py", line 7, in <module>
    import dci.context
  File "/home/guillaume/workspace/dci-client/venv/lib64/python3.7/site-packages/dci/context.py", line 18, in <module>
    from requests import compat
ModuleNotFoundError: No module named 'requests'
```

IMO you should create a script for publishing on pypi which test that the installation works (`pip install -e .`)

**Comment by goneri** [comment]
Fixed by 02d2a7dab7969c7b2bcf43e4211a8fa60407a879.
